manifest_version: 1

organization:
  name: My Foosball Community

players:
  - name: David Zhang
    alias:
      - dz
      - David
    level: beginner

events:
  - id: 978d68fa-5f9e-49df-b576-12b29299c215
    name: 2023-9 Yangsheng Tournament
    points: 50
    url: https://asiatablesoccer.glide.page/dl/tournaments/s/8e7f85/r/f-b0muR4SxeWXgwzIeg-gg
